version: '3.8'

services:
  # Servicio de la app Host
  host:
    build:
      context: ./apps/host
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - SITE=${SITE:-default}
    ports:
      - "${HOST_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db

  # Servicio de la app Quicksearch
  quicksearch:
    build:
      context: ./apps/quicksearch
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - SITE=${SITE:-default}
    ports:
      - "${QUICKSEARCH_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db

  # Servicio para Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.3.0
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  # Servicio para Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:2.3.0
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  # Servicio para inicializar Airflow
  airflow-init:
    image: apache/airflow:2.3.0
    restart: on-failure
    entrypoint: >
      /bin/bash -c
      "airflow db init &&
       airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  # Servicio de la base de datos PostgreSQL para Airflow
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

volumes:
  postgres-db-volume:
